apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rtvb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0047-tenant/ci1t-830-0047-app/devfile-sample-rtvb@sha256:f769b9280f849829d2c111693dbb6bba45dcc81d1f3cc6c66e44cb7a93fe9f08
        name: my-nodejs
        resources: {}
status: {}
