apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rtvb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rtvb
    app.kubernetes.io/part-of: ci1t-830-0047-app
  name: devfile-sample-rtvb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rtvb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rtvb
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0047-tenant/ci1t-830-0047-app/devfile-sample-rtvb@sha256:f769b9280f849829d2c111693dbb6bba45dcc81d1f3cc6c66e44cb7a93fe9f08
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
